const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const UNAUTHORIZED = 401;
const CONFLICTING_REQUEST = 409;
const FORBIDDEN = 403;
module.exports = {
  // eslint-disable-next-line max-len
  BAD_REQUEST, NOT_FOUND, INTERNAL_SERVER_ERROR, CONFLICTING_REQUEST, UNAUTHORIZED, FORBIDDEN,
};